description = 'GRAL example applications'

ext.pomName = 'GRAL examples'
ext.pomDescription = description

apply plugin: 'application'

dependencies {
	implementation project(':gral-core')
	// The examples display their plots in a window.
	implementation project(':gral-swing')
}

application {
	mainClass = 'de.erichseifert.gral.examples.Browser'
}

jar {
	manifest {
		attributes(
			'Main-Class': application.mainClass.get(),
			'Automatic-Module-Name': 'de.erichseifert.gral.examples',
			'Implementation-Title': project.description,
			'Implementation-Version': project.version,
		)
	}
}
