/*
 * GRAL: GRAphing Library for Java(R)
 *
 * (C) Copyright 2009-2011 Erich Seifert <dev[at]erichseifert.de>,
 * Michael Seifert <michael.seifert[at]gmx.net>
 *
 * This file is part of GRAL.
 *
 * GRAL is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GRAL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with GRAL.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.erichseifert.gral;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.RowIdLifetime;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.sql.Time;
import java.sql.Timestamp;
import java.sql.Types;
import java.util.Calendar;
import java.util.Map;
import java.util.Properties;

import de.erichseifert.gral.data.DataSource;
import de.erichseifert.gral.data.DummyData;

public class DummyJdbc implements Connection {
	private final DataSource data;

	public DummyJdbc(DataSource data) {
		this.data = data;
	}

	public void clearWarnings() throws SQLException {
	}

	public void close() throws SQLException {
	}

	public void commit() throws SQLException {
	}

	public Array createArrayOf(String typeName, Object[] elements)
			throws SQLException {
		return null;
	}

	public Blob createBlob() throws SQLException {
		return null;
	}

	public Clob createClob() throws SQLException {
		return null;
	}

	public NClob createNClob() throws SQLException {
		return null;
	}

	public SQLXML createSQLXML() throws SQLException {
		return null;
	}

	public Statement createStatement() throws SQLException {
		return null;
	}

	public Statement createStatement(int resultSetType, int resultSetConcurrency)
			throws SQLException {
		return null;
	}

	public Statement createStatement(int resultSetType,
			int resultSetConcurrency, int resultSetHoldability)
			throws SQLException {
		return null;
	}

	public Struct createStruct(String typeName, Object[] attributes)
			throws SQLException {
		return null;
	}

	public boolean getAutoCommit() throws SQLException {
		return false;
	}

	public String getCatalog() throws SQLException {
		return null;
	}

	public Properties getClientInfo() throws SQLException {
		return null;
	}

	public String getClientInfo(String name) throws SQLException {
		return null;
	}

	public int getHoldability() throws SQLException {
		return 0;
	}

	public DatabaseMetaData getMetaData() throws SQLException {
		return new DummyDataBaseMetaData(data);
	}

	public int getTransactionIsolation() throws SQLException {
		return 0;
	}

	public Map<String, Class<?>> getTypeMap() throws SQLException {
		return null;
	}

	public SQLWarning getWarnings() throws SQLException {
		return null;
	}

	public boolean isClosed() throws SQLException {
		return false;
	}

	public boolean isReadOnly() throws SQLException {
		return false;
	}

	public boolean isValid(int timeout) throws SQLException {
		return false;
	}

	public String nativeSQL(String sql) throws SQLException {
		return null;
	}

	public CallableStatement prepareCall(String sql) throws SQLException {
		return null;
	}

	public CallableStatement prepareCall(String sql, int resultSetType,
			int resultSetConcurrency) throws SQLException {
		return null;
	}

	public CallableStatement prepareCall(String sql, int resultSetType,
			int resultSetConcurrency, int resultSetHoldability)
			throws SQLException {
		return null;
	}

	public PreparedStatement prepareStatement(String sql) throws SQLException {
		return new DummyPreparedStatement(data);
	}

	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys)
			throws SQLException {
		return new DummyPreparedStatement(data);
	}

	public PreparedStatement prepareStatement(String sql, int[] columnIndexes)
			throws SQLException {
		return new DummyPreparedStatement(data);
	}

	public PreparedStatement prepareStatement(String sql, String[] columnNames)
			throws SQLException {
		return new DummyPreparedStatement(data);
	}

	public PreparedStatement prepareStatement(String sql, int resultSetType,
			int resultSetConcurrency) throws SQLException {
		return prepareStatement(sql, resultSetType, resultSetConcurrency, ResultSet.HOLD_CURSORS_OVER_COMMIT);
	}

	public PreparedStatement prepareStatement(String sql, int resultSetType,
			int resultSetConcurrency, int resultSetHoldability)
			throws SQLException {
		if (sql.toUpperCase().startsWith("SELECT COUNT(*) FROM ")) {
			return new DummyPreparedStatement(new DummyData(1, 1, data.getRowCount()));
		}
		return new DummyPreparedStatement(data);
	}

	public void releaseSavepoint(Savepoint savepoint) throws SQLException {

	}

	public void rollback() throws SQLException {

	}

	public void rollback(Savepoint savepoint) throws SQLException {

	}

	public void setAutoCommit(boolean autoCommit) throws SQLException {

	}

	public void setCatalog(String catalog) throws SQLException {

	}

	public void setClientInfo(Properties properties)
			throws SQLClientInfoException {

	}

	public void setClientInfo(String name, String value)
			throws SQLClientInfoException {

	}

	public void setHoldability(int holdability) throws SQLException {

	}

	public void setReadOnly(boolean readOnly) throws SQLException {

	}

	public Savepoint setSavepoint() throws SQLException {
		return null;
	}

	public Savepoint setSavepoint(String name) throws SQLException {
		return null;
	}

	public void setTransactionIsolation(int level) throws SQLException {

	}

	public void setTypeMap(Map<String, Class<?>> map) throws SQLException {

	}

	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		return false;
	}

	public <T> T unwrap(Class<T> iface) throws SQLException {
		return null;
	}
}

class DummyDataBaseMetaData implements DatabaseMetaData {
	private final DataSource data;

	public DummyDataBaseMetaData(DataSource data) {
		this.data = data;
	}

	public boolean allProceduresAreCallable() throws SQLException {
		return false;
	}

	public boolean allTablesAreSelectable() throws SQLException {
		return false;
	}

	public boolean autoCommitFailureClosesAllResultSets() throws SQLException {
		return false;
	}

	public boolean dataDefinitionCausesTransactionCommit() throws SQLException {
		return false;
	}

	public boolean dataDefinitionIgnoredInTransactions() throws SQLException {
		return false;
	}

	public boolean deletesAreDetected(int type) throws SQLException {
		return false;
	}

	public boolean doesMaxRowSizeIncludeBlobs() throws SQLException {
		return false;
	}

	public ResultSet getAttributes(String catalog, String schemaPattern,
			String typeNamePattern, String attributeNamePattern)
			throws SQLException {
		return null;
	}

	public ResultSet getBestRowIdentifier(String catalog, String schema,
			String table, int scope, boolean nullable) throws SQLException {
		return null;
	}

	public String getCatalogSeparator() throws SQLException {
		return null;
	}

	public String getCatalogTerm() throws SQLException {
		return null;
	}

	public ResultSet getCatalogs() throws SQLException {
		return null;
	}

	public ResultSet getClientInfoProperties() throws SQLException {
		return null;
	}

	public ResultSet getColumnPrivileges(String catalog, String schema,
			String table, String columnNamePattern) throws SQLException {
		return null;
	}

	public ResultSet getColumns(String catalog, String schemaPattern,
			String tableNamePattern, String columnNamePattern)
			throws SQLException {
		return null;
	}

	public Connection getConnection() throws SQLException {
		return null;
	}

	public ResultSet getCrossReference(String parentCatalog,
			String parentSchema, String parentTable, String foreignCatalog,
			String foreignSchema, String foreignTable) throws SQLException {
		return null;
	}

	public int getDatabaseMajorVersion() throws SQLException {
		return 0;
	}

	public int getDatabaseMinorVersion() throws SQLException {
		return 0;
	}

	public String getDatabaseProductName() throws SQLException {
		return null;
	}

	public String getDatabaseProductVersion() throws SQLException {
		return null;
	}

	public int getDefaultTransactionIsolation() throws SQLException {
		return 0;
	}

	public int getDriverMajorVersion() {
		return 0;
	}

	public int getDriverMinorVersion() {
		return 0;
	}

	public String getDriverName() throws SQLException {
		return null;
	}

	public String getDriverVersion() throws SQLException {
		return null;
	}

	public ResultSet getExportedKeys(String catalog, String schema, String table)
			throws SQLException {
		return null;
	}

	public String getExtraNameCharacters() throws SQLException {
		return null;
	}

	public ResultSet getFunctionColumns(String catalog, String schemaPattern,
			String functionNamePattern, String columnNamePattern)
			throws SQLException {
		return null;
	}

	public ResultSet getFunctions(String catalog, String schemaPattern,
			String functionNamePattern) throws SQLException {
		return null;
	}

	public String getIdentifierQuoteString() throws SQLException {
		return null;
	}

	public ResultSet getImportedKeys(String catalog, String schema, String table)
			throws SQLException {
		return null;
	}

	public ResultSet getIndexInfo(String catalog, String schema, String table,
			boolean unique, boolean approximate) throws SQLException {
		return null;
	}

	public int getJDBCMajorVersion() throws SQLException {
		return 0;
	}

	public int getJDBCMinorVersion() throws SQLException {
		return 0;
	}

	public int getMaxBinaryLiteralLength() throws SQLException {
		return 0;
	}

	public int getMaxCatalogNameLength() throws SQLException {
		return 0;
	}

	public int getMaxCharLiteralLength() throws SQLException {
		return 0;
	}

	public int getMaxColumnNameLength() throws SQLException {
		return 0;
	}

	public int getMaxColumnsInGroupBy() throws SQLException {
		return 0;
	}

	public int getMaxColumnsInIndex() throws SQLException {
		return 0;
	}

	public int getMaxColumnsInOrderBy() throws SQLException {
		return 0;
	}

	public int getMaxColumnsInSelect() throws SQLException {
		return 0;
	}

	public int getMaxColumnsInTable() throws SQLException {
		return 0;
	}

	public int getMaxConnections() throws SQLException {
		return 0;
	}

	public int getMaxCursorNameLength() throws SQLException {
		return 0;
	}

	public int getMaxIndexLength() throws SQLException {
		return 0;
	}

	public int getMaxProcedureNameLength() throws SQLException {
		return 0;
	}

	public int getMaxRowSize() throws SQLException {
		return 0;
	}

	public int getMaxSchemaNameLength() throws SQLException {
		return 0;
	}

	public int getMaxStatementLength() throws SQLException {
		return 0;
	}

	public int getMaxStatements() throws SQLException {
		return 0;
	}

	public int getMaxTableNameLength() throws SQLException {
		return 0;
	}

	public int getMaxTablesInSelect() throws SQLException {
		return 0;
	}

	public int getMaxUserNameLength() throws SQLException {
		return 0;
	}

	public String getNumericFunctions() throws SQLException {
		return null;
	}

	public ResultSet getPrimaryKeys(String catalog, String schema, String table)
			throws SQLException {
		return null;
	}

	public ResultSet getProcedureColumns(String catalog, String schemaPattern,
			String procedureNamePattern, String columnNamePattern)
			throws SQLException {
		return null;
	}

	public String getProcedureTerm() throws SQLException {
		return null;
	}

	public ResultSet getProcedures(String catalog, String schemaPattern,
			String procedureNamePattern) throws SQLException {
		return null;
	}

	public int getResultSetHoldability() throws SQLException {
		return 0;
	}

	public RowIdLifetime getRowIdLifetime() throws SQLException {
		return null;
	}

	public String getSQLKeywords() throws SQLException {
		return null;
	}

	public int getSQLStateType() throws SQLException {
		return 0;
	}

	public String getSchemaTerm() throws SQLException {
		return null;
	}

	public ResultSet getSchemas() throws SQLException {
		return null;
	}

	public ResultSet getSchemas(String catalog, String schemaPattern)
			throws SQLException {
		return null;
	}

	public String getSearchStringEscape() throws SQLException {
		return null;
	}

	public String getStringFunctions() throws SQLException {
		return null;
	}

	public ResultSet getSuperTables(String catalog, String schemaPattern,
			String tableNamePattern) throws SQLException {
		return null;
	}

	public ResultSet getSuperTypes(String catalog, String schemaPattern,
			String typeNamePattern) throws SQLException {
		return null;
	}

	public String getSystemFunctions() throws SQLException {
		return null;
	}

	public ResultSet getTablePrivileges(String catalog, String schemaPattern,
			String tableNamePattern) throws SQLException {
		return null;
	}

	public ResultSet getTableTypes() throws SQLException {
		return null;
	}

	public ResultSet getTables(String catalog, String schemaPattern,
			String tableNamePattern, String[] types) throws SQLException {
		return null;
	}

	public String getTimeDateFunctions() throws SQLException {
		return null;
	}

	public ResultSet getTypeInfo() throws SQLException {
		return null;
	}

	public ResultSet getUDTs(String catalog, String schemaPattern,
			String typeNamePattern, int[] types) throws SQLException {
		return null;
	}

	public String getURL() throws SQLException {
		return null;
	}

	public String getUserName() throws SQLException {
		return null;
	}

	public ResultSet getVersionColumns(String catalog, String schema,
			String table) throws SQLException {
		return null;
	}

	public boolean insertsAreDetected(int type) throws SQLException {
		return false;
	}

	public boolean isCatalogAtStart() throws SQLException {
		return false;
	}

	public boolean isReadOnly() throws SQLException {
		return false;
	}

	public boolean locatorsUpdateCopy() throws SQLException {
		return false;
	}

	public boolean nullPlusNonNullIsNull() throws SQLException {
		return false;
	}

	public boolean nullsAreSortedAtEnd() throws SQLException {
		return false;
	}

	public boolean nullsAreSortedAtStart() throws SQLException {
		return false;
	}

	public boolean nullsAreSortedHigh() throws SQLException {
		return false;
	}

	public boolean nullsAreSortedLow() throws SQLException {
		return false;
	}

	public boolean othersDeletesAreVisible(int type) throws SQLException {
		return false;
	}

	public boolean othersInsertsAreVisible(int type) throws SQLException {
		return false;
	}

	public boolean othersUpdatesAreVisible(int type) throws SQLException {
		return false;
	}

	public boolean ownDeletesAreVisible(int type) throws SQLException {
		return false;
	}

	public boolean ownInsertsAreVisible(int type) throws SQLException {
		return false;
	}

	public boolean ownUpdatesAreVisible(int type) throws SQLException {
		return false;
	}

	public boolean storesLowerCaseIdentifiers() throws SQLException {
		return false;
	}

	public boolean storesLowerCaseQuotedIdentifiers() throws SQLException {
		return false;
	}

	public boolean storesMixedCaseIdentifiers() throws SQLException {
		return false;
	}

	public boolean storesMixedCaseQuotedIdentifiers() throws SQLException {
		return false;
	}

	public boolean storesUpperCaseIdentifiers() throws SQLException {
		return false;
	}

	public boolean storesUpperCaseQuotedIdentifiers() throws SQLException {
		return false;
	}

	public boolean supportsANSI92EntryLevelSQL() throws SQLException {
		return false;
	}

	public boolean supportsANSI92FullSQL() throws SQLException {
		return false;
	}

	public boolean supportsANSI92IntermediateSQL() throws SQLException {
		return false;
	}

	public boolean supportsAlterTableWithAddColumn() throws SQLException {
		return false;
	}

	public boolean supportsAlterTableWithDropColumn() throws SQLException {
		return false;
	}

	public boolean supportsBatchUpdates() throws SQLException {
		return false;
	}

	public boolean supportsCatalogsInDataManipulation() throws SQLException {
		return false;
	}

	public boolean supportsCatalogsInIndexDefinitions() throws SQLException {
		return false;
	}

	public boolean supportsCatalogsInPrivilegeDefinitions() throws SQLException {
		return false;
	}

	public boolean supportsCatalogsInProcedureCalls() throws SQLException {
		return false;
	}

	public boolean supportsCatalogsInTableDefinitions() throws SQLException {
		return false;
	}

	public boolean supportsColumnAliasing() throws SQLException {
		return false;
	}

	public boolean supportsConvert() throws SQLException {
		return false;
	}

	public boolean supportsConvert(int fromType, int toType)
			throws SQLException {
		return false;
	}

	public boolean supportsCoreSQLGrammar() throws SQLException {
		return false;
	}

	public boolean supportsCorrelatedSubqueries() throws SQLException {
		return false;
	}

	public boolean supportsDataDefinitionAndDataManipulationTransactions()
			throws SQLException {
		return false;
	}

	public boolean supportsDataManipulationTransactionsOnly()
			throws SQLException {
		return false;
	}

	public boolean supportsDifferentTableCorrelationNames() throws SQLException {
		return false;
	}

	public boolean supportsExpressionsInOrderBy() throws SQLException {
		return false;
	}

	public boolean supportsExtendedSQLGrammar() throws SQLException {
		return false;
	}

	public boolean supportsFullOuterJoins() throws SQLException {
		return false;
	}

	public boolean supportsGetGeneratedKeys() throws SQLException {
		return false;
	}

	public boolean supportsGroupBy() throws SQLException {
		return false;
	}

	public boolean supportsGroupByBeyondSelect() throws SQLException {
		return false;
	}

	public boolean supportsGroupByUnrelated() throws SQLException {
		return false;
	}

	public boolean supportsIntegrityEnhancementFacility() throws SQLException {
		return false;
	}

	public boolean supportsLikeEscapeClause() throws SQLException {
		return false;
	}

	public boolean supportsLimitedOuterJoins() throws SQLException {
		return false;
	}

	public boolean supportsMinimumSQLGrammar() throws SQLException {
		return false;
	}

	public boolean supportsMixedCaseIdentifiers() throws SQLException {
		return false;
	}

	public boolean supportsMixedCaseQuotedIdentifiers() throws SQLException {
		return false;
	}

	public boolean supportsMultipleOpenResults() throws SQLException {
		return false;
	}

	public boolean supportsMultipleResultSets() throws SQLException {
		return false;
	}

	public boolean supportsMultipleTransactions() throws SQLException {
		return false;
	}

	public boolean supportsNamedParameters() throws SQLException {
		return false;
	}

	public boolean supportsNonNullableColumns() throws SQLException {
		return false;
	}

	public boolean supportsOpenCursorsAcrossCommit() throws SQLException {
		return false;
	}

	public boolean supportsOpenCursorsAcrossRollback() throws SQLException {
		return false;
	}

	public boolean supportsOpenStatementsAcrossCommit() throws SQLException {
		return false;
	}

	public boolean supportsOpenStatementsAcrossRollback() throws SQLException {
		return false;
	}

	public boolean supportsOrderByUnrelated() throws SQLException {
		return false;
	}

	public boolean supportsOuterJoins() throws SQLException {
		return false;
	}

	public boolean supportsPositionedDelete() throws SQLException {
		return false;
	}

	public boolean supportsPositionedUpdate() throws SQLException {
		return false;
	}

	public boolean supportsResultSetConcurrency(int type, int concurrency)
			throws SQLException {
		return false;
	}

	public boolean supportsResultSetHoldability(int holdability)
			throws SQLException {
		return false;
	}

	public boolean supportsResultSetType(int type) throws SQLException {
		return false;
	}

	public boolean supportsSavepoints() throws SQLException {
		return false;
	}

	public boolean supportsSchemasInDataManipulation() throws SQLException {
		return false;
	}

	public boolean supportsSchemasInIndexDefinitions() throws SQLException {
		return false;
	}

	public boolean supportsSchemasInPrivilegeDefinitions() throws SQLException {
		return false;
	}

	public boolean supportsSchemasInProcedureCalls() throws SQLException {
		return false;
	}

	public boolean supportsSchemasInTableDefinitions() throws SQLException {
		return false;
	}

	public boolean supportsSelectForUpdate() throws SQLException {
		return false;
	}

	public boolean supportsStatementPooling() throws SQLException {
		return false;
	}

	public boolean supportsStoredFunctionsUsingCallSyntax() throws SQLException {
		return false;
	}

	public boolean supportsStoredProcedures() throws SQLException {
		return false;
	}

	public boolean supportsSubqueriesInComparisons() throws SQLException {
		return false;
	}

	public boolean supportsSubqueriesInExists() throws SQLException {
		return false;
	}

	public boolean supportsSubqueriesInIns() throws SQLException {
		return false;
	}

	public boolean supportsSubqueriesInQuantifieds() throws SQLException {
		return false;
	}

	public boolean supportsTableCorrelationNames() throws SQLException {
		return false;
	}

	public boolean supportsTransactionIsolationLevel(int level)
			throws SQLException {
		return false;
	}

	public boolean supportsTransactions() throws SQLException {
		return false;
	}

	public boolean supportsUnion() throws SQLException {
		return false;
	}

	public boolean supportsUnionAll() throws SQLException {
		return false;
	}

	public boolean updatesAreDetected(int type) throws SQLException {
		return false;
	}

	public boolean usesLocalFilePerTable() throws SQLException {
		return false;
	}

	public boolean usesLocalFiles() throws SQLException {
		return false;
	}

	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		return false;
	}

	public <T> T unwrap(Class<T> iface) throws SQLException {
		return null;
	}
}

class DummyResultSet implements ResultSet {
	private final DataSource data;
	private int rowIndex = -1;
	private boolean closed;

	public DummyResultSet(DataSource data) {
		this.data = data;
	}

	public boolean absolute(int row) throws SQLException {
		rowIndex = row - 1;
		return !isBeforeFirst() && !isAfterLast();
	}

	public void afterLast() throws SQLException {
		rowIndex = data.getRowCount();
	}

	public void beforeFirst() throws SQLException {
		rowIndex = -1;
	}

	public void cancelRowUpdates() throws SQLException {

	}

	public void clearWarnings() throws SQLException {

	}

	public void close() throws SQLException {
		closed = true;
	}

	public void deleteRow() throws SQLException {

	}

	public int findColumn(String columnLabel) throws SQLException {
		return 0;
	}

	public boolean first() throws SQLException {
		rowIndex = 0;
		return !isBeforeFirst() && !isAfterLast();
	}

	public Array getArray(int columnIndex) throws SQLException {
		return null;
	}

	public Array getArray(String columnLabel) throws SQLException {
		return null;
	}

	public InputStream getAsciiStream(int columnIndex) throws SQLException {
		return null;
	}

	public InputStream getAsciiStream(String columnLabel) throws SQLException {
		return null;
	}

	public BigDecimal getBigDecimal(int columnIndex) throws SQLException {
		return null;
	}

	public BigDecimal getBigDecimal(String columnLabel) throws SQLException {
		return null;
	}

	public BigDecimal getBigDecimal(int columnIndex, int scale)
			throws SQLException {
		return null;
	}

	public BigDecimal getBigDecimal(String columnLabel, int scale)
			throws SQLException {
		return null;
	}

	public InputStream getBinaryStream(int columnIndex) throws SQLException {
		return null;
	}

	public InputStream getBinaryStream(String columnLabel) throws SQLException {
		return null;
	}

	public Blob getBlob(int columnIndex) throws SQLException {
		return null;
	}

	public Blob getBlob(String columnLabel) throws SQLException {
		return null;
	}

	public boolean getBoolean(int columnIndex) throws SQLException {
		return false;
	}

	public boolean getBoolean(String columnLabel) throws SQLException {
		return false;
	}

	public byte getByte(int columnIndex) throws SQLException {
		return ((Number) data.get(columnIndex - 1, rowIndex)).byteValue();
	}

	public byte getByte(String columnLabel) throws SQLException {
		return 0;
	}

	public byte[] getBytes(int columnIndex) throws SQLException {
		return null;
	}

	public byte[] getBytes(String columnLabel) throws SQLException {
		return null;
	}

	public Reader getCharacterStream(int columnIndex) throws SQLException {
		return null;
	}

	public Reader getCharacterStream(String columnLabel) throws SQLException {
		return null;
	}

	public Clob getClob(int columnIndex) throws SQLException {
		return null;
	}

	public Clob getClob(String columnLabel) throws SQLException {
		return null;
	}

	public int getConcurrency() throws SQLException {
		return 0;
	}

	public String getCursorName() throws SQLException {
		return null;
	}

	public Date getDate(int columnIndex) throws SQLException {
		return (Date) data.get(columnIndex - 1, rowIndex);
	}

	public Date getDate(String columnLabel) throws SQLException {
		return null;
	}

	public Date getDate(int columnIndex, Calendar cal) throws SQLException {
		// TODO Use calender
		return (Date) data.get(columnIndex - 1, rowIndex);
	}

	public Date getDate(String columnLabel, Calendar cal) throws SQLException {
		return null;
	}

	public double getDouble(int columnIndex) throws SQLException {
		return ((Number) data.get(columnIndex - 1, rowIndex)).doubleValue();
	}

	public double getDouble(String columnLabel) throws SQLException {
		return 0;
	}

	public int getFetchDirection() throws SQLException {
		return 0;
	}

	public int getFetchSize() throws SQLException {
		return 0;
	}

	public float getFloat(int columnIndex) throws SQLException {
		return ((Number) data.get(columnIndex - 1, rowIndex)).floatValue();
	}

	public float getFloat(String columnLabel) throws SQLException {
		return 0;
	}

	public int getHoldability() throws SQLException {
		return 0;
	}

	public int getInt(int columnIndex) throws SQLException {
		return ((Number) data.get(columnIndex - 1, rowIndex)).intValue();
	}

	public int getInt(String columnLabel) throws SQLException {
		return 0;
	}

	public long getLong(int columnIndex) throws SQLException {
		return ((Number) data.get(columnIndex - 1, rowIndex)).longValue();
	}

	public long getLong(String columnLabel) throws SQLException {
		return 0;
	}

	public ResultSetMetaData getMetaData() throws SQLException {
		return null;
	}

	public Reader getNCharacterStream(int columnIndex) throws SQLException {
		return null;
	}

	public Reader getNCharacterStream(String columnLabel) throws SQLException {
		return null;
	}

	public NClob getNClob(int columnIndex) throws SQLException {
		return null;
	}

	public NClob getNClob(String columnLabel) throws SQLException {
		return null;
	}

	public String getNString(int columnIndex) throws SQLException {
		return getString(columnIndex);
	}

	public String getNString(String columnLabel) throws SQLException {
		return null;
	}

	public Object getObject(int columnIndex) throws SQLException {
		return data.get(columnIndex - 1, rowIndex);
	}

	public Object getObject(String columnLabel) throws SQLException {
		return null;
	}

	public Object getObject(int columnIndex, Map<String, Class<?>> map)
			throws SQLException {
		return null;
	}

	public Object getObject(String columnLabel, Map<String, Class<?>> map)
			throws SQLException {
		return null;
	}

	public Ref getRef(int columnIndex) throws SQLException {
		return null;
	}

	public Ref getRef(String columnLabel) throws SQLException {
		return null;
	}

	public int getRow() throws SQLException {
		return 0;
	}

	public RowId getRowId(int columnIndex) throws SQLException {
		return null;
	}

	public RowId getRowId(String columnLabel) throws SQLException {
		return null;
	}

	public SQLXML getSQLXML(int columnIndex) throws SQLException {
		return null;
	}

	public SQLXML getSQLXML(String columnLabel) throws SQLException {
		return null;
	}

	public short getShort(int columnIndex) throws SQLException {
		return ((Number) data.get(columnIndex - 1, rowIndex)).shortValue();
	}

	public short getShort(String columnLabel) throws SQLException {
		return 0;
	}

	public Statement getStatement() throws SQLException {
		return null;
	}

	public String getString(int columnIndex) throws SQLException {
		return String.valueOf(data.get(columnIndex - 1, rowIndex));
	}

	public String getString(String columnLabel) throws SQLException {
		return null;
	}

	public Time getTime(int columnIndex) throws SQLException {
		return (Time) data.get(columnIndex - 1, rowIndex);
	}

	public Time getTime(String columnLabel) throws SQLException {
		return null;
	}

	public Time getTime(int columnIndex, Calendar cal) throws SQLException {
		return null;
	}

	public Time getTime(String columnLabel, Calendar cal) throws SQLException {
		return null;
	}

	public Timestamp getTimestamp(int columnIndex) throws SQLException {
		return (Timestamp) data.get(columnIndex - 1, rowIndex);
	}

	public Timestamp getTimestamp(String columnLabel) throws SQLException {
		return null;
	}

	public Timestamp getTimestamp(int columnIndex, Calendar cal)
			throws SQLException {
		return null;
	}

	public Timestamp getTimestamp(String columnLabel, Calendar cal)
			throws SQLException {
		return null;
	}

	public int getType() throws SQLException {
		return 0;
	}

	public URL getURL(int columnIndex) throws SQLException {
		return null;
	}

	public URL getURL(String columnLabel) throws SQLException {
		return null;
	}

	public InputStream getUnicodeStream(int columnIndex) throws SQLException {
		return null;
	}

	public InputStream getUnicodeStream(String columnLabel) throws SQLException {
		return null;
	}

	public SQLWarning getWarnings() throws SQLException {
		return null;
	}

	public void insertRow() throws SQLException {

	}

	public boolean isAfterLast() throws SQLException {
		return rowIndex >= data.getRowCount();
	}

	public boolean isBeforeFirst() throws SQLException {
		return rowIndex < 0;
	}

	public boolean isClosed() throws SQLException {
		return closed;
	}

	public boolean isFirst() throws SQLException {
		return rowIndex == 0;
	}

	public boolean isLast() throws SQLException {
		return rowIndex == data.getRowCount() - 1;
	}

	public boolean last() throws SQLException {
		rowIndex = data.getRowCount() - 1;
		return rowIndex >= 0 && rowIndex < data.getRowCount();
	}

	public void moveToCurrentRow() throws SQLException {

	}

	public void moveToInsertRow() throws SQLException {

	}

	public boolean next() throws SQLException {
		rowIndex++;
		if (rowIndex > data.getRowCount()) {
			rowIndex = data.getRowCount();
		}
		return !isBeforeFirst() && !isAfterLast();
	}

	public boolean previous() throws SQLException {
		rowIndex--;
		if (rowIndex < 0) {
			rowIndex = -1;
		}
		return !isBeforeFirst() && !isAfterLast();
	}

	public void refreshRow() throws SQLException {

	}

	public boolean relative(int rows) throws SQLException {
		return false;
	}

	public boolean rowDeleted() throws SQLException {
		return false;
	}

	public boolean rowInserted() throws SQLException {
		return false;
	}

	public boolean rowUpdated() throws SQLException {
		return false;
	}

	public void setFetchDirection(int direction) throws SQLException {

	}

	public void setFetchSize(int rows) throws SQLException {

	}

	public void updateArray(int columnIndex, Array x) throws SQLException {

	}

	public void updateArray(String columnLabel, Array x) throws SQLException {

	}

	public void updateAsciiStream(int columnIndex, InputStream x)
			throws SQLException {

	}

	public void updateAsciiStream(String columnLabel, InputStream x)
			throws SQLException {

	}

	public void updateAsciiStream(int columnIndex, InputStream x, int length)
			throws SQLException {

	}

	public void updateAsciiStream(String columnLabel, InputStream x, int length)
			throws SQLException {

	}

	public void updateAsciiStream(int columnIndex, InputStream x, long length)
			throws SQLException {

	}

	public void updateAsciiStream(String columnLabel, InputStream x, long length)
			throws SQLException {

	}

	public void updateBigDecimal(int columnIndex, BigDecimal x)
			throws SQLException {

	}

	public void updateBigDecimal(String columnLabel, BigDecimal x)
			throws SQLException {

	}

	public void updateBinaryStream(int columnIndex, InputStream x)
			throws SQLException {

	}

	public void updateBinaryStream(String columnLabel, InputStream x)
			throws SQLException {

	}

	public void updateBinaryStream(int columnIndex, InputStream x, int length)
			throws SQLException {

	}

	public void updateBinaryStream(String columnLabel, InputStream x, int length)
			throws SQLException {

	}

	public void updateBinaryStream(int columnIndex, InputStream x, long length)
			throws SQLException {

	}

	public void updateBinaryStream(String columnLabel, InputStream x,
			long length) throws SQLException {

	}

	public void updateBlob(int columnIndex, Blob x) throws SQLException {

	}

	public void updateBlob(String columnLabel, Blob x) throws SQLException {

	}

	public void updateBlob(int columnIndex, InputStream inputStream)
			throws SQLException {

	}

	public void updateBlob(String columnLabel, InputStream inputStream)
			throws SQLException {

	}

	public void updateBlob(int columnIndex, InputStream inputStream, long length)
			throws SQLException {

	}

	public void updateBlob(String columnLabel, InputStream inputStream,
			long length) throws SQLException {

	}

	public void updateBoolean(int columnIndex, boolean x) throws SQLException {

	}

	public void updateBoolean(String columnLabel, boolean x)
			throws SQLException {

	}

	public void updateByte(int columnIndex, byte x) throws SQLException {

	}

	public void updateByte(String columnLabel, byte x) throws SQLException {

	}

	public void updateBytes(int columnIndex, byte[] x) throws SQLException {

	}

	public void updateBytes(String columnLabel, byte[] x) throws SQLException {

	}

	public void updateCharacterStream(int columnIndex, Reader x)
			throws SQLException {

	}

	public void updateCharacterStream(String columnLabel, Reader reader)
			throws SQLException {

	}

	public void updateCharacterStream(int columnIndex, Reader x, int length)
			throws SQLException {

	}

	public void updateCharacterStream(String columnLabel, Reader reader,
			int length) throws SQLException {

	}

	public void updateCharacterStream(int columnIndex, Reader x, long length)
			throws SQLException {

	}

	public void updateCharacterStream(String columnLabel, Reader reader,
			long length) throws SQLException {

	}

	public void updateClob(int columnIndex, Clob x) throws SQLException {

	}

	public void updateClob(String columnLabel, Clob x) throws SQLException {

	}

	public void updateClob(int columnIndex, Reader reader) throws SQLException {

	}

	public void updateClob(String columnLabel, Reader reader)
			throws SQLException {

	}

	public void updateClob(int columnIndex, Reader reader, long length)
			throws SQLException {

	}

	public void updateClob(String columnLabel, Reader reader, long length)
			throws SQLException {

	}

	public void updateDate(int columnIndex, Date x) throws SQLException {

	}

	public void updateDate(String columnLabel, Date x) throws SQLException {

	}

	public void updateDouble(int columnIndex, double x) throws SQLException {

	}

	public void updateDouble(String columnLabel, double x) throws SQLException {

	}

	public void updateFloat(int columnIndex, float x) throws SQLException {

	}

	public void updateFloat(String columnLabel, float x) throws SQLException {

	}

	public void updateInt(int columnIndex, int x) throws SQLException {

	}

	public void updateInt(String columnLabel, int x) throws SQLException {

	}

	public void updateLong(int columnIndex, long x) throws SQLException {

	}

	public void updateLong(String columnLabel, long x) throws SQLException {

	}

	public void updateNCharacterStream(int columnIndex, Reader x)
			throws SQLException {

	}

	public void updateNCharacterStream(String columnLabel, Reader reader)
			throws SQLException {

	}

	public void updateNCharacterStream(int columnIndex, Reader x, long length)
			throws SQLException {

	}

	public void updateNCharacterStream(String columnLabel, Reader reader,
			long length) throws SQLException {

	}

	public void updateNClob(int columnIndex, NClob nClob) throws SQLException {

	}

	public void updateNClob(String columnLabel, NClob nClob)
			throws SQLException {

	}

	public void updateNClob(int columnIndex, Reader reader) throws SQLException {

	}

	public void updateNClob(String columnLabel, Reader reader)
			throws SQLException {

	}

	public void updateNClob(int columnIndex, Reader reader, long length)
			throws SQLException {

	}

	public void updateNClob(String columnLabel, Reader reader, long length)
			throws SQLException {

	}

	public void updateNString(int columnIndex, String nString)
			throws SQLException {

	}

	public void updateNString(String columnLabel, String nString)
			throws SQLException {

	}

	public void updateNull(int columnIndex) throws SQLException {

	}

	public void updateNull(String columnLabel) throws SQLException {

	}

	public void updateObject(int columnIndex, Object x) throws SQLException {

	}

	public void updateObject(String columnLabel, Object x) throws SQLException {

	}

	public void updateObject(int columnIndex, Object x, int scaleOrLength)
			throws SQLException {

	}

	public void updateObject(String columnLabel, Object x, int scaleOrLength)
			throws SQLException {

	}

	public void updateRef(int columnIndex, Ref x) throws SQLException {

	}

	public void updateRef(String columnLabel, Ref x) throws SQLException {

	}

	public void updateRow() throws SQLException {

	}

	public void updateRowId(int columnIndex, RowId x) throws SQLException {

	}

	public void updateRowId(String columnLabel, RowId x) throws SQLException {

	}

	public void updateSQLXML(int columnIndex, SQLXML xmlObject)
			throws SQLException {

	}

	public void updateSQLXML(String columnLabel, SQLXML xmlObject)
			throws SQLException {

	}

	public void updateShort(int columnIndex, short x) throws SQLException {

	}

	public void updateShort(String columnLabel, short x) throws SQLException {

	}

	public void updateString(int columnIndex, String x) throws SQLException {

	}

	public void updateString(String columnLabel, String x) throws SQLException {

	}

	public void updateTime(int columnIndex, Time x) throws SQLException {

	}

	public void updateTime(String columnLabel, Time x) throws SQLException {

	}

	public void updateTimestamp(int columnIndex, Timestamp x)
			throws SQLException {

	}

	public void updateTimestamp(String columnLabel, Timestamp x)
			throws SQLException {

	}

	public boolean wasNull() throws SQLException {
		return false;
	}

	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		return false;
	}

	public <T> T unwrap(Class<T> iface) throws SQLException {
		return null;
	}
}

class DummyResultSetMetaData implements ResultSetMetaData {
	private final DataSource data;

	public DummyResultSetMetaData(DataSource data) {
		this.data = data;
	}

	public String getCatalogName(int column) throws SQLException {
		return null;
	}

	public String getColumnClassName(int column) throws SQLException {
		return null;
	}

	public int getColumnCount() throws SQLException {
		return data.getColumnCount();
	}

	public int getColumnDisplaySize(int column) throws SQLException {
		return 0;
	}

	public String getColumnLabel(int column) throws SQLException {
		return null;
	}

	public String getColumnName(int column) throws SQLException {
		return null;
	}

	public int getColumnType(int column) throws SQLException {
		return getJdbcColumnType(column);
	}

	private int getJdbcColumnType(int column) {
		Class<? extends Comparable<?>> javaType = data.getColumnTypes()[column - 1];
		if (Byte.class.equals(javaType)) {
			return Types.TINYINT;
		} else if (Short.class.equals(javaType)) {
			return Types.SMALLINT;
		} else if (Integer.class.equals(javaType)) {
			return Types.INTEGER;
		} else if (Long.class.equals(javaType)) {
			return Types.BIGINT;
		} else if (Byte.class.equals(javaType)) {
			return Types.TINYINT;
		} else if (Float.class.equals(javaType)) {
			return Types.REAL;
		} else if (Double.class.equals(javaType)) {
			return Types.FLOAT;
		} else if (Date.class.equals(javaType)) {
			return Types.DATE;
		} else if (Time.class.equals(javaType)) {
			return Types.TIME;
		} else if (Timestamp.class.equals(javaType)) {
			return Types.TIMESTAMP;
		} else if (String.class.equals(javaType)) {
			return Types.VARCHAR;
		}

		throw new IllegalArgumentException(String.format("Unkown java data type: %s", javaType.getName()));
	}

	public String getColumnTypeName(int column) throws SQLException {
		return null;
	}

	public int getPrecision(int column) throws SQLException {
		return 0;
	}

	public int getScale(int column) throws SQLException {
		return 0;
	}

	public String getSchemaName(int column) throws SQLException {
		return null;
	}

	public String getTableName(int column) throws SQLException {
		return null;
	}

	public boolean isAutoIncrement(int column) throws SQLException {
		return false;
	}

	public boolean isCaseSensitive(int column) throws SQLException {
		return false;
	}

	public boolean isCurrency(int column) throws SQLException {
		return false;
	}

	public boolean isDefinitelyWritable(int column) throws SQLException {
		return false;
	}

	public int isNullable(int column) throws SQLException {
		return 0;
	}

	public boolean isReadOnly(int column) throws SQLException {
		return false;
	}

	public boolean isSearchable(int column) throws SQLException {
		return false;
	}

	public boolean isSigned(int column) throws SQLException {
		return false;
	}

	public boolean isWritable(int column) throws SQLException {
		return false;
	}

	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		return false;
	}

	public <T> T unwrap(Class<T> iface) throws SQLException {
		return null;
	}
}

class DummyPreparedStatement implements PreparedStatement {
	private final DataSource data;

	public DummyPreparedStatement(DataSource data) {
		this.data = data;
	}

	public void addBatch() throws SQLException {

	}

	public void clearParameters() throws SQLException {

	}

	public boolean execute() throws SQLException {
		return false;
	}

	public ResultSet executeQuery() throws SQLException {
		return new DummyResultSet(data);
	}

	public int executeUpdate() throws SQLException {
		return 0;
	}

	public ResultSetMetaData getMetaData() throws SQLException {
		return new DummyResultSetMetaData(data);
	}

	public ParameterMetaData getParameterMetaData() throws SQLException {
		return null;
	}

	public void setArray(int parameterIndex, Array x) throws SQLException {

	}

	public void setAsciiStream(int parameterIndex, InputStream x)
			throws SQLException {

	}

	public void setAsciiStream(int parameterIndex, InputStream x, int length)
			throws SQLException {

	}

	public void setAsciiStream(int parameterIndex, InputStream x, long length)
			throws SQLException {

	}

	public void setBigDecimal(int parameterIndex, BigDecimal x)
			throws SQLException {

	}

	public void setBinaryStream(int parameterIndex, InputStream x)
			throws SQLException {

	}

	public void setBinaryStream(int parameterIndex, InputStream x, int length)
			throws SQLException {

	}

	public void setBinaryStream(int parameterIndex, InputStream x, long length)
			throws SQLException {

	}

	public void setBlob(int parameterIndex, Blob x) throws SQLException {

	}

	public void setBlob(int parameterIndex, InputStream inputStream)
			throws SQLException {

	}

	public void setBlob(int parameterIndex, InputStream inputStream, long length)
			throws SQLException {

	}

	public void setBoolean(int parameterIndex, boolean x) throws SQLException {

	}

	public void setByte(int parameterIndex, byte x) throws SQLException {

	}

	public void setBytes(int parameterIndex, byte[] x) throws SQLException {

	}

	public void setCharacterStream(int parameterIndex, Reader reader)
			throws SQLException {

	}

	public void setCharacterStream(int parameterIndex, Reader reader, int length)
			throws SQLException {

	}

	public void setCharacterStream(int parameterIndex, Reader reader,
			long length) throws SQLException {

	}

	public void setClob(int parameterIndex, Clob x) throws SQLException {

	}

	public void setClob(int parameterIndex, Reader reader) throws SQLException {

	}

	public void setClob(int parameterIndex, Reader reader, long length)
			throws SQLException {

	}

	public void setDate(int parameterIndex, Date x) throws SQLException {

	}

	public void setDate(int parameterIndex, Date x, Calendar cal)
			throws SQLException {

	}

	public void setDouble(int parameterIndex, double x) throws SQLException {

	}

	public void setFloat(int parameterIndex, float x) throws SQLException {

	}

	public void setInt(int parameterIndex, int x) throws SQLException {

	}

	public void setLong(int parameterIndex, long x) throws SQLException {

	}

	public void setNCharacterStream(int parameterIndex, Reader value)
			throws SQLException {

	}

	public void setNCharacterStream(int parameterIndex, Reader value,
			long length) throws SQLException {

	}

	public void setNClob(int parameterIndex, NClob value) throws SQLException {

	}

	public void setNClob(int parameterIndex, Reader reader) throws SQLException {

	}

	public void setNClob(int parameterIndex, Reader reader, long length)
			throws SQLException {

	}

	public void setNString(int parameterIndex, String value)
			throws SQLException {

	}

	public void setNull(int parameterIndex, int sqlType) throws SQLException {

	}

	public void setNull(int parameterIndex, int sqlType, String typeName)
			throws SQLException {

	}

	public void setObject(int parameterIndex, Object x) throws SQLException {

	}

	public void setObject(int parameterIndex, Object x, int targetSqlType)
			throws SQLException {

	}

	public void setObject(int parameterIndex, Object x, int targetSqlType,
			int scaleOrLength) throws SQLException {

	}

	public void setRef(int parameterIndex, Ref x) throws SQLException {

	}

	public void setRowId(int parameterIndex, RowId x) throws SQLException {

	}

	public void setSQLXML(int parameterIndex, SQLXML xmlObject)
			throws SQLException {

	}

	public void setShort(int parameterIndex, short x) throws SQLException {

	}

	public void setString(int parameterIndex, String x) throws SQLException {

	}

	public void setTime(int parameterIndex, Time x) throws SQLException {

	}

	public void setTime(int parameterIndex, Time x, Calendar cal)
			throws SQLException {

	}

	public void setTimestamp(int parameterIndex, Timestamp x)
			throws SQLException {

	}

	public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal)
			throws SQLException {

	}

	public void setURL(int parameterIndex, URL x) throws SQLException {

	}

	public void setUnicodeStream(int parameterIndex, InputStream x, int length)
			throws SQLException {

	}

	public void addBatch(String sql) throws SQLException {

	}

	public void cancel() throws SQLException {

	}

	public void clearBatch() throws SQLException {

	}

	public void clearWarnings() throws SQLException {

	}

	public void close() throws SQLException {

	}

	public boolean execute(String sql) throws SQLException {
		return false;
	}

	public boolean execute(String sql, int autoGeneratedKeys)
			throws SQLException {
		return false;
	}

	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		return false;
	}

	public boolean execute(String sql, String[] columnNames)
			throws SQLException {
		return false;
	}

	public int[] executeBatch() throws SQLException {
		return null;
	}

	public ResultSet executeQuery(String sql) throws SQLException {
		return null;
	}

	public int executeUpdate(String sql) throws SQLException {
		return 0;
	}

	public int executeUpdate(String sql, int autoGeneratedKeys)
			throws SQLException {
		return 0;
	}

	public int executeUpdate(String sql, int[] columnIndexes)
			throws SQLException {
		return 0;
	}

	public int executeUpdate(String sql, String[] columnNames)
			throws SQLException {
		return 0;
	}

	public Connection getConnection() throws SQLException {
		return null;
	}

	public int getFetchDirection() throws SQLException {
		return 0;
	}

	public int getFetchSize() throws SQLException {
		return 0;
	}

	public ResultSet getGeneratedKeys() throws SQLException {
		return null;
	}

	public int getMaxFieldSize() throws SQLException {
		return 0;
	}

	public int getMaxRows() throws SQLException {
		return 0;
	}

	public boolean getMoreResults() throws SQLException {
		return false;
	}

	public boolean getMoreResults(int current) throws SQLException {
		return false;
	}

	public int getQueryTimeout() throws SQLException {
		return 0;
	}

	public ResultSet getResultSet() throws SQLException {
		return null;
	}

	public int getResultSetConcurrency() throws SQLException {
		return 0;
	}

	public int getResultSetHoldability() throws SQLException {
		return 0;
	}

	public int getResultSetType() throws SQLException {
		return 0;
	}

	public int getUpdateCount() throws SQLException {
		return 0;
	}

	public SQLWarning getWarnings() throws SQLException {
		return null;
	}

	public boolean isClosed() throws SQLException {
		return false;
	}

	public boolean isPoolable() throws SQLException {
		return false;
	}

	public void setCursorName(String name) throws SQLException {

	}

	public void setEscapeProcessing(boolean enable) throws SQLException {

	}

	public void setFetchDirection(int direction) throws SQLException {

	}

	public void setFetchSize(int rows) throws SQLException {

	}

	public void setMaxFieldSize(int max) throws SQLException {

	}

	public void setMaxRows(int max) throws SQLException {

	}

	public void setPoolable(boolean poolable) throws SQLException {

	}

	public void setQueryTimeout(int seconds) throws SQLException {

	}

	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		return false;
	}

	public <T> T unwrap(Class<T> iface) throws SQLException {
		return null;
	}
}